name: Deploy to Git Branch

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm ci

      - name: Build estático
        run: npm run build

      - name: Push a rama deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.LED_TOKEN }}
          branch: deploy
          folder: out
          clean: true
